FROM quay.io/fedora/fedora-toolbox:44@sha256:f957cbe226b7eaf1b7c65cf7023a43fb60c8c57c99f678ce7ff67beab5a40fcc AS builder
COPY ./toolboxes/fedora-toolbox/packages.fedora /toolbox-packages

# Set up dependencies
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    dnf upgrade -y && \
    dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release-mesa && \
    dnf -y config-manager setopt "*fedora*".exclude="mesa-*" && \
    dnf distro-sync -y --repo='terra-mesa' mesa-filesystem && \
    dnf install -y \
        $(cat toolbox-packages | xargs) && \
    rm /toolbox-packages && \
    git clone https://github.com/89luca89/distrobox.git --single-branch /tmp/distrobox && \
    cp /tmp/distrobox/distrobox-host-exec /usr/bin/distrobox-host-exec && \
    wget https://github.com/1player/host-spawn/releases/download/$(cat /tmp/distrobox/distrobox-host-exec | grep host_spawn_version= | cut -d "\"" -f 2)/host-spawn-$(uname -m) -O /usr/bin/host-spawn && \
    chmod +x /usr/bin/host-spawn && \
    rm -drf /tmp/distrobox && \
    dnf install -y 'dnf-command(copr)' && \
    dnf copr enable -y kylegospo/distrobox-utils && \
    dnf install -y \
        xdg-utils-distrobox && \
    ln -s /usr/bin/distrobox-host-exec /usr/bin/flatpak && \
    dnf install -y \
        "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
        "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm" && \
    dnf install -y \
        intel-media-driver \
        libva-nvidia-driver

# https://github.com/coreos/chunkah
FROM quay.io/coreos/chunkah:latest AS chunkah

# Rechunk
ARG SOURCE_DATE_EPOCH
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
RUN --mount=from=builder,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
    chunkah build \
    --max-layers 64 \
    --label=com.github.containers.toolbox=true \
    --label=name=fedora-toolbox \
    --label=usage="This image is meant to be used with the toolbox or distrobox command" \
    --label=summary="A cloud-native terminal experience powered by Fedora" \
    --label=maintainer=me@kylegospodneti.ch \
    > /run/src/out.ociarchive

# Deploy final chunked image
FROM oci-archive:out.ociarchive
